"""Add human-readable fields

Revision ID: 3031c865fede
Revises: 30a89b31c7a7
Create Date: 2025-08-21 22:14:04.735028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3031c865fede"
down_revision: Union[str, None] = "30a89b31c7a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "title", sa.String(length=128), nullable=False, server_default="Untitled"
        ),
    )
    op.add_column(
        "datasets",
        sa.Column(
            "description", sa.String(length=512), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "mlmodels",
        sa.Column(
            "title", sa.String(length=128), nullable=False, server_default="Untitled"
        ),
    )
    op.add_column(
        "mlmodels",
        sa.Column(
            "description", sa.String(length=512), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "predict_tasks",
        sa.Column(
            "title", sa.String(length=128), nullable=False, server_default="Untitled"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("predict_tasks", "title")
    op.drop_column("mlmodels", "description")
    op.drop_column("mlmodels", "title")
    op.drop_column("datasets", "description")
    op.drop_column("datasets", "title")
    # ### end Alembic commands ###
