- name: Run autotests and down
  block:
    - name: Start autotests
      command: >
        docker compose \
        -f ../docker-compose.autotest.yaml \
        --env-file ../.env.autotest \
        up \
        --abort-on-container-exit \
        --exit-code-from api-autotest
      environment:
        TEST_REPORT_FILE: "/app/test-report.xml"
        DB_PASSWORD: "{{ app_db_password }}"
        DB_USER: "{{ app_db_user }}"

    - name: Copy test result logs
      command: >
        docker compose \
        -f ../docker-compose.autotest.yaml \
        --env-file ../.env.autotest \
        cp "api-autotest:/app/test-report.xml" "{{ app_test_report_file }}"
      when: app_test_report_file is defined

  always:
    - name: Down autotests and clear volumes
      command: >
        docker compose \
        -f docker-compose.autotest.yaml \
        --env-file .env.autotest \
        down -v
